import "./globals.css";
import { Inter } from "next/font/google";
import WebGL from "@/components/WebGL";
import Overlay from "@/components/Overlay";
import Cursor from "@/components/Cursor";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "nk studio",
//   description: "Generated by Shahbaj Sheikh",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WebGL />
        <Overlay />
        <Cursor />
        <main id="scrollContainer">{children}</main>
      </body>
    </html>
  );
}
